name: Modify Noto CJK

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Get fonts
        run: |
          mkdir ./fonts
          cd ./fonts
          for link in $(echo ${{ vars.FONT_LINKS }}) ; do curl -OL $link ; done
          ls

      # https://github.com/fonttools/unicodedata2/issues/52
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install Pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install east-asian-spacing
        run: pipx install east-asian-spacing

      - name: Patch chws, vchw, halt and vhal by east-asian-spacing
        run: east-asian-spacing -o ./eas ./fonts/*

      - name: Checkout nototools repo
        uses: actions/checkout@v3
        with:
          repository: notofonts/nototools
          ref: v0.2.17
          path: './nototools'

      - name: Install notofonttools
        run: |
          cd ./nototools
          pip install -r requirements.txt
          pip install -e .

      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: './current'

      - name: Patch for Android
        run: python ./current/scripts/subset_fonts.py -o ./subset4android ./eas/*

      - name: Copy changed font
        run: |
          cmake -E make_directory ./current/${{ vars.FONT_DIR }}
          cp ./subset4android/* ./current/${{ vars.FONT_DIR }}

      - name: Push new fonts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update fonts ${{ vars.FONT_DIR }}
          repository: ./current
